"""Frozen explicit initial ResearchNavigator schema.

Revision ID: 0001
Revises: None
Create Date: 2026-08-26
"""

import sqlalchemy as sa

from alembic import op

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "papers",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("normalized_title", sa.Text(), nullable=False),
        sa.Column("translated_title", sa.Text(), nullable=True),
        sa.Column("abstract", sa.Text(), nullable=True),
        sa.Column("publication_year", sa.Integer(), nullable=True),
        sa.Column("publication_date_text", sa.String(length=20), nullable=True),
        sa.Column("authors_json", sa.Text(), nullable=False),
        sa.Column("venue", sa.Text(), nullable=True),
        sa.Column("venue_type", sa.String(length=120), nullable=True),
        sa.Column("doi", sa.String(length=300), nullable=True),
        sa.Column("arxiv_id", sa.String(length=100), nullable=True),
        sa.Column("external_ids_json", sa.Text(), nullable=False),
        sa.Column("source_urls_json", sa.Text(), nullable=False),
        sa.Column("publisher_url", sa.Text(), nullable=True),
        sa.Column("pdf_url", sa.Text(), nullable=True),
        sa.Column("open_access_status", sa.String(length=80), nullable=True),
        sa.Column("citation_count", sa.Integer(), nullable=True),
        sa.Column("reference_count", sa.Integer(), nullable=True),
        sa.Column("fields_of_study_json", sa.Text(), nullable=False),
        sa.Column("concepts_json", sa.Text(), nullable=False),
        sa.Column("keywords_json", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_papers_arxiv_id"), "papers", ["arxiv_id"], unique=True)
    op.create_index(op.f("ix_papers_doi"), "papers", ["doi"], unique=True)
    op.create_index(
        op.f("ix_papers_normalized_title"), "papers", ["normalized_title"], unique=False
    )
    op.create_index(
        "ix_papers_normalized_title_year",
        "papers",
        ["normalized_title", "publication_year"],
        unique=False,
    )
    op.create_index(
        op.f("ix_papers_publication_year"), "papers", ["publication_year"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=512), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "favorites",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("paper_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["paper_id"], ["papers.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "paper_id", name="uq_favorite_user_paper"),
    )
    op.create_index(op.f("ix_favorites_paper_id"), "favorites", ["paper_id"], unique=False)
    op.create_index(op.f("ix_favorites_user_id"), "favorites", ["user_id"], unique=False)
    op.create_table(
        "notes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("paper_id", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("note_type", sa.String(length=40), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["paper_id"], ["papers.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_notes_paper_id"), "notes", ["paper_id"], unique=False)
    op.create_index(op.f("ix_notes_user_id"), "notes", ["user_id"], unique=False)
    op.create_table(
        "paper_documents",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("paper_id", sa.Integer(), nullable=False),
        sa.Column("source_type", sa.String(length=80), nullable=False),
        sa.Column("evidence_level", sa.String(length=80), nullable=False),
        sa.Column("original_filename", sa.String(length=200), nullable=False),
        sa.Column("stored_path", sa.Text(), nullable=False),
        sa.Column("mime_type", sa.String(length=120), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("page_count", sa.Integer(), nullable=False),
        sa.Column("rights_confirmed", sa.Boolean(), nullable=False),
        sa.Column("ingestion_version", sa.String(length=80), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["paper_id"], ["papers.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "paper_id", "sha256", name="uq_document_user_paper_hash"),
    )
    op.create_index(
        op.f("ix_paper_documents_paper_id"), "paper_documents", ["paper_id"], unique=False
    )
    op.create_index(op.f("ix_paper_documents_sha256"), "paper_documents", ["sha256"], unique=False)
    op.create_index(
        op.f("ix_paper_documents_user_id"), "paper_documents", ["user_id"], unique=False
    )
    op.create_table(
        "paper_sources",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("paper_id", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=80), nullable=False),
        sa.Column("source_id", sa.String(length=500), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("raw_hash", sa.String(length=64), nullable=True),
        sa.Column("is_fixture", sa.Boolean(), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["paper_id"], ["papers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("paper_id", "source", "source_id", name="uq_paper_source_identity"),
    )
    op.create_index(op.f("ix_paper_sources_paper_id"), "paper_sources", ["paper_id"], unique=False)
    op.create_index(op.f("ix_paper_sources_source"), "paper_sources", ["source"], unique=False)
    op.create_table(
        "reading_status",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("paper_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("progress", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["paper_id"], ["papers.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "paper_id", name="uq_reading_status_user_paper"),
    )
    op.create_index(
        op.f("ix_reading_status_paper_id"), "reading_status", ["paper_id"], unique=False
    )
    op.create_index(op.f("ix_reading_status_user_id"), "reading_status", ["user_id"], unique=False)
    op.create_table(
        "research_profiles",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("stage", sa.String(length=80), nullable=True),
        sa.Column("major", sa.String(length=160), nullable=True),
        sa.Column("broad_direction", sa.String(length=240), nullable=True),
        sa.Column("keywords_json", sa.Text(), nullable=False),
        sa.Column("excluded_terms_json", sa.Text(), nullable=False),
        sa.Column("preferences_json", sa.Text(), nullable=False),
        sa.Column("compute_constraints", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_research_profiles_user_id"), "research_profiles", ["user_id"], unique=True
    )
    op.create_table(
        "research_projects",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=240), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("broad_direction", sa.String(length=240), nullable=True),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "name", name="uq_project_user_name"),
    )
    op.create_index(
        op.f("ix_research_projects_user_id"), "research_projects", ["user_id"], unique=False
    )
    op.create_index(
        "ix_research_projects_user_updated",
        "research_projects",
        ["user_id", "updated_at"],
        unique=False,
    )
    op.create_table(
        "session_tokens",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_session_tokens_token_hash"), "session_tokens", ["token_hash"], unique=True
    )
    op.create_index(op.f("ix_session_tokens_user_id"), "session_tokens", ["user_id"], unique=False)
    op.create_table(
        "tags",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "name", name="uq_tag_user_name"),
    )
    op.create_index(op.f("ix_tags_user_id"), "tags", ["user_id"], unique=False)
    op.create_table(
        "agent_runs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column("workflow_type", sa.String(length=80), nullable=False),
        sa.Column("workflow_version", sa.String(length=80), nullable=False),
        sa.Column("prompt_version", sa.String(length=80), nullable=True),
        sa.Column("model_provider", sa.String(length=120), nullable=True),
        sa.Column("model_name", sa.String(length=160), nullable=True),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("input_json", sa.Text(), nullable=False),
        sa.Column("output_json", sa.Text(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("output_hash", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["research_projects.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_agent_runs_project_id"), "agent_runs", ["project_id"], unique=False)
    op.create_index(op.f("ix_agent_runs_run_id"), "agent_runs", ["run_id"], unique=True)
    op.create_index(op.f("ix_agent_runs_user_id"), "agent_runs", ["user_id"], unique=False)
    op.create_table(
        "gap_candidates",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("gap_type", sa.String(length=120), nullable=False),
        sa.Column("claim", sa.Text(), nullable=False),
        sa.Column("scope", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=60), nullable=False),
        sa.Column("evidence_matrix_json", sa.Text(), nullable=False),
        sa.Column("supporting_evidence_json", sa.Text(), nullable=False),
        sa.Column("adjacent_work_json", sa.Text(), nullable=False),
        sa.Column("counter_evidence_json", sa.Text(), nullable=False),
        sa.Column("challenge_queries_json", sa.Text(), nullable=False),
        sa.Column("data_sources_json", sa.Text(), nullable=False),
        sa.Column("coverage_json", sa.Text(), nullable=False),
        sa.Column("confidence", sa.String(length=20), nullable=False),
        sa.Column("risk_factors_json", sa.Text(), nullable=False),
        sa.Column("minimal_validation_json", sa.Text(), nullable=False),
        sa.Column("suggested_research_question", sa.Text(), nullable=False),
        sa.Column("not_novelty_proof", sa.Boolean(), nullable=False),
        sa.Column("challenge_completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("human_confirmation_note", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["research_projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_gap_candidates_project_id"), "gap_candidates", ["project_id"], unique=False
    )
    op.create_index(op.f("ix_gap_candidates_status"), "gap_candidates", ["status"], unique=False)
    op.create_index(op.f("ix_gap_candidates_user_id"), "gap_candidates", ["user_id"], unique=False)
    op.create_index(
        "ix_gap_candidates_user_project", "gap_candidates", ["user_id", "project_id"], unique=False
    )
    op.create_table(
        "jobs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column("job_type", sa.String(length=80), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("payload_json", sa.Text(), nullable=False),
        sa.Column("result_json", sa.Text(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("locked_by", sa.String(length=120), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["research_projects.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_jobs_project_id"), "jobs", ["project_id"], unique=False)
    op.create_index(op.f("ix_jobs_status"), "jobs", ["status"], unique=False)
    op.create_index("ix_jobs_status_created", "jobs", ["status", "created_at"], unique=False)
    op.create_index(op.f("ix_jobs_user_id"), "jobs", ["user_id"], unique=False)
    op.create_table(
        "paper_analyses",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("paper_id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column("evidence_level", sa.String(length=80), nullable=False),
        sa.Column("analysis_version", sa.String(length=80), nullable=False),
        sa.Column("analysis_json", sa.Text(), nullable=False),
        sa.Column("direction_similarity_json", sa.Text(), nullable=False),
        sa.Column("reproduction_assessment_json", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["paper_id"], ["papers.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["research_projects.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_paper_analyses_lookup",
        "paper_analyses",
        ["user_id", "paper_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_paper_analyses_paper_id"), "paper_analyses", ["paper_id"], unique=False
    )
    op.create_index(
        op.f("ix_paper_analyses_project_id"), "paper_analyses", ["project_id"], unique=False
    )
    op.create_index(op.f("ix_paper_analyses_user_id"), "paper_analyses", ["user_id"], unique=False)
    op.create_table(
        "paper_chunks",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.Column("paper_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("section", sa.String(length=120), nullable=False),
        sa.Column("page_start", sa.Integer(), nullable=False),
        sa.Column("page_end", sa.Integer(), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("text_hash", sa.String(length=64), nullable=False),
        sa.Column("vector_json", sa.Text(), nullable=False),
        sa.Column("source_type", sa.String(length=80), nullable=False),
        sa.Column("evidence_level", sa.String(length=80), nullable=False),
        sa.Column("ingestion_version", sa.String(length=80), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["document_id"], ["paper_documents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["paper_id"], ["papers.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document_id", "chunk_index", name="uq_document_chunk_index"),
    )
    op.create_index("ix_paper_chunks_access", "paper_chunks", ["paper_id", "user_id"], unique=False)
    op.create_index(
        op.f("ix_paper_chunks_document_id"), "paper_chunks", ["document_id"], unique=False
    )
    op.create_index(op.f("ix_paper_chunks_paper_id"), "paper_chunks", ["paper_id"], unique=False)
    op.create_index(op.f("ix_paper_chunks_user_id"), "paper_chunks", ["user_id"], unique=False)
    op.create_table(
        "paper_tags",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("paper_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["paper_id"], ["papers.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tag_id"], ["tags.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "paper_id", "tag_id", name="uq_paper_tag_user"),
    )
    op.create_index(op.f("ix_paper_tags_paper_id"), "paper_tags", ["paper_id"], unique=False)
    op.create_index(op.f("ix_paper_tags_tag_id"), "paper_tags", ["tag_id"], unique=False)
    op.create_index(op.f("ix_paper_tags_user_id"), "paper_tags", ["user_id"], unique=False)
    op.create_table(
        "recommendations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column("paper_id", sa.Integer(), nullable=False),
        sa.Column("category", sa.String(length=80), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("evidence_json", sa.Text(), nullable=False),
        sa.Column("recommendation_version", sa.String(length=80), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["paper_id"], ["papers.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["research_projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id",
            "project_id",
            "paper_id",
            "category",
            name="uq_recommendation_user_project_paper_category",
        ),
    )
    op.create_index(
        op.f("ix_recommendations_paper_id"), "recommendations", ["paper_id"], unique=False
    )
    op.create_index(
        op.f("ix_recommendations_project_id"), "recommendations", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_recommendations_user_id"), "recommendations", ["user_id"], unique=False
    )
    op.create_index(
        "ix_recommendations_user_project_score",
        "recommendations",
        ["user_id", "project_id", "score"],
        unique=False,
    )
    op.create_table(
        "search_sessions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column("query", sa.Text(), nullable=False),
        sa.Column("filters_json", sa.Text(), nullable=False),
        sa.Column("source_status_json", sa.Text(), nullable=False),
        sa.Column("result_ids_json", sa.Text(), nullable=False),
        sa.Column("result_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["research_projects.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_search_sessions_project_id"), "search_sessions", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_search_sessions_user_id"), "search_sessions", ["user_id"], unique=False
    )
    op.create_table(
        "gap_evidence",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("gap_id", sa.Integer(), nullable=False),
        sa.Column("paper_id", sa.Integer(), nullable=True),
        sa.Column("evidence_role", sa.String(length=40), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("source_query", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["gap_id"], ["gap_candidates.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["paper_id"], ["papers.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_gap_evidence_gap_id"), "gap_evidence", ["gap_id"], unique=False)
    op.create_index(op.f("ix_gap_evidence_paper_id"), "gap_evidence", ["paper_id"], unique=False)
    op.create_table(
        "job_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(length=60), nullable=False),
        sa.Column("detail_json", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_job_events_job_created", "job_events", ["job_id", "created_at"], unique=False
    )
    op.create_index(op.f("ix_job_events_job_id"), "job_events", ["job_id"], unique=False)
    op.create_index(op.f("ix_job_events_user_id"), "job_events", ["user_id"], unique=False)
    op.create_table(
        "research_plans",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("gap_id", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("objective", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["gap_id"], ["gap_candidates.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["project_id"], ["research_projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_research_plans_gap_id"), "research_plans", ["gap_id"], unique=False)
    op.create_index(
        op.f("ix_research_plans_project_id"), "research_plans", ["project_id"], unique=False
    )
    op.create_index(op.f("ix_research_plans_user_id"), "research_plans", ["user_id"], unique=False)
    op.create_index(
        "ix_research_plans_user_project", "research_plans", ["user_id", "project_id"], unique=False
    )
    op.create_table(
        "plan_items",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("plan_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("category", sa.String(length=80), nullable=False),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["plan_id"], ["research_plans.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_plan_items_plan_id"), "plan_items", ["plan_id"], unique=False)
    op.create_index(
        "ix_plan_items_plan_sequence", "plan_items", ["plan_id", "sequence"], unique=False
    )
    op.create_index(op.f("ix_plan_items_user_id"), "plan_items", ["user_id"], unique=False)
    op.execute(
        "CREATE VIRTUAL TABLE paper_chunks_fts "
        "USING fts5(chunk_id UNINDEXED, document_id UNINDEXED, "
        "paper_id UNINDEXED, user_id UNINDEXED, section, text, "
        "tokenize='unicode61')"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE IF EXISTS paper_chunks_fts")
    op.drop_index(op.f("ix_plan_items_user_id"), table_name="plan_items")
    op.drop_index("ix_plan_items_plan_sequence", table_name="plan_items")
    op.drop_index(op.f("ix_plan_items_plan_id"), table_name="plan_items")
    op.drop_table("plan_items")
    op.drop_index("ix_research_plans_user_project", table_name="research_plans")
    op.drop_index(op.f("ix_research_plans_user_id"), table_name="research_plans")
    op.drop_index(op.f("ix_research_plans_project_id"), table_name="research_plans")
    op.drop_index(op.f("ix_research_plans_gap_id"), table_name="research_plans")
    op.drop_table("research_plans")
    op.drop_index(op.f("ix_job_events_user_id"), table_name="job_events")
    op.drop_index(op.f("ix_job_events_job_id"), table_name="job_events")
    op.drop_index("ix_job_events_job_created", table_name="job_events")
    op.drop_table("job_events")
    op.drop_index(op.f("ix_gap_evidence_paper_id"), table_name="gap_evidence")
    op.drop_index(op.f("ix_gap_evidence_gap_id"), table_name="gap_evidence")
    op.drop_table("gap_evidence")
    op.drop_index(op.f("ix_search_sessions_user_id"), table_name="search_sessions")
    op.drop_index(op.f("ix_search_sessions_project_id"), table_name="search_sessions")
    op.drop_table("search_sessions")
    op.drop_index("ix_recommendations_user_project_score", table_name="recommendations")
    op.drop_index(op.f("ix_recommendations_user_id"), table_name="recommendations")
    op.drop_index(op.f("ix_recommendations_project_id"), table_name="recommendations")
    op.drop_index(op.f("ix_recommendations_paper_id"), table_name="recommendations")
    op.drop_table("recommendations")
    op.drop_index(op.f("ix_paper_tags_user_id"), table_name="paper_tags")
    op.drop_index(op.f("ix_paper_tags_tag_id"), table_name="paper_tags")
    op.drop_index(op.f("ix_paper_tags_paper_id"), table_name="paper_tags")
    op.drop_table("paper_tags")
    op.drop_index(op.f("ix_paper_chunks_user_id"), table_name="paper_chunks")
    op.drop_index(op.f("ix_paper_chunks_paper_id"), table_name="paper_chunks")
    op.drop_index(op.f("ix_paper_chunks_document_id"), table_name="paper_chunks")
    op.drop_index("ix_paper_chunks_access", table_name="paper_chunks")
    op.drop_table("paper_chunks")
    op.drop_index(op.f("ix_paper_analyses_user_id"), table_name="paper_analyses")
    op.drop_index(op.f("ix_paper_analyses_project_id"), table_name="paper_analyses")
    op.drop_index(op.f("ix_paper_analyses_paper_id"), table_name="paper_analyses")
    op.drop_index("ix_paper_analyses_lookup", table_name="paper_analyses")
    op.drop_table("paper_analyses")
    op.drop_index(op.f("ix_jobs_user_id"), table_name="jobs")
    op.drop_index("ix_jobs_status_created", table_name="jobs")
    op.drop_index(op.f("ix_jobs_status"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_project_id"), table_name="jobs")
    op.drop_table("jobs")
    op.drop_index("ix_gap_candidates_user_project", table_name="gap_candidates")
    op.drop_index(op.f("ix_gap_candidates_user_id"), table_name="gap_candidates")
    op.drop_index(op.f("ix_gap_candidates_status"), table_name="gap_candidates")
    op.drop_index(op.f("ix_gap_candidates_project_id"), table_name="gap_candidates")
    op.drop_table("gap_candidates")
    op.drop_index(op.f("ix_agent_runs_user_id"), table_name="agent_runs")
    op.drop_index(op.f("ix_agent_runs_run_id"), table_name="agent_runs")
    op.drop_index(op.f("ix_agent_runs_project_id"), table_name="agent_runs")
    op.drop_table("agent_runs")
    op.drop_index(op.f("ix_tags_user_id"), table_name="tags")
    op.drop_table("tags")
    op.drop_index(op.f("ix_session_tokens_user_id"), table_name="session_tokens")
    op.drop_index(op.f("ix_session_tokens_token_hash"), table_name="session_tokens")
    op.drop_table("session_tokens")
    op.drop_index("ix_research_projects_user_updated", table_name="research_projects")
    op.drop_index(op.f("ix_research_projects_user_id"), table_name="research_projects")
    op.drop_table("research_projects")
    op.drop_index(op.f("ix_research_profiles_user_id"), table_name="research_profiles")
    op.drop_table("research_profiles")
    op.drop_index(op.f("ix_reading_status_user_id"), table_name="reading_status")
    op.drop_index(op.f("ix_reading_status_paper_id"), table_name="reading_status")
    op.drop_table("reading_status")
    op.drop_index(op.f("ix_paper_sources_source"), table_name="paper_sources")
    op.drop_index(op.f("ix_paper_sources_paper_id"), table_name="paper_sources")
    op.drop_table("paper_sources")
    op.drop_index(op.f("ix_paper_documents_user_id"), table_name="paper_documents")
    op.drop_index(op.f("ix_paper_documents_sha256"), table_name="paper_documents")
    op.drop_index(op.f("ix_paper_documents_paper_id"), table_name="paper_documents")
    op.drop_table("paper_documents")
    op.drop_index(op.f("ix_notes_user_id"), table_name="notes")
    op.drop_index(op.f("ix_notes_paper_id"), table_name="notes")
    op.drop_table("notes")
    op.drop_index(op.f("ix_favorites_user_id"), table_name="favorites")
    op.drop_index(op.f("ix_favorites_paper_id"), table_name="favorites")
    op.drop_table("favorites")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_papers_publication_year"), table_name="papers")
    op.drop_index("ix_papers_normalized_title_year", table_name="papers")
    op.drop_index(op.f("ix_papers_normalized_title"), table_name="papers")
    op.drop_index(op.f("ix_papers_doi"), table_name="papers")
    op.drop_index(op.f("ix_papers_arxiv_id"), table_name="papers")
    op.drop_table("papers")
    # ### end Alembic commands ###
